[colors.primary]
background = '#282828'
foreground = '#dfbf8e'

[colors.normal]
black   = '#665c54'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#e78a4e'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#dfbf8e'

[colors.bright]
black   = '#928374'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#e3a84e'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#dfbf8e'

[font]
size = 10

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[window]
opacity = 1
